name: obanor-wp-ecf
volumes:
  db_data_wp:
services:
  wordpress_ecf_db:
    container_name: obanor-wp-ecf-db
    image: mariadb:11.8.5
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data_wp:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=db_ecf_wordpress
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    ports: ['3306:3306']
  wordpress:
    container_name: obanor-wp-ecf-web
    image: wordpress:6.9.2-php8.5-apache
    ports: ['8081:80']
    restart: unless-stopped
    depends_on: ['wordpress_ecf_db']
    environment:
      - WORDPRESS_DB_HOST=wordpress_ecf_db
      - WORDPRESS_DB_NAME=db_ecf_wordpress
      - WORDPRESS_DB_USER=username
      - WORDPRESS_DB_PASSWORD=password
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
